language: node_js
node_js:
- '0.11'
- '0.10'
before_script:
- export PATH="$PATH:$(npm bin)"
script:
- gulp lint
- npm test
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate < ./coverage/lcov.info
deploy:
  provider: npm
  email: bvdrucker@gmail.com
  api_key:
    secure: GQqARs7Cus12AWQ29b/5uKfFD1+DPFF67kzCEuNhgmax7ITzE0O4FuucaO8JqB7JReoozvbN21QmC0M4zouB/+rcMd3H9h2aAUYMflT1Hr2wgGGJoB1sshTwZ8AQ25s76neOjhGwV8g+5asXS0AOhXPosXOVE6+KdvuXXbMc7xQ=
  on:
    tags: true
    all_branches: true
    repo: bendrucker/clearbit-node
env:
  global:
    secure: CHoeYn6R9p4vQ96KkysrCSIiN7J0EU1x1jNuevgYVgVol+b5ukvDVUBTaSEzeSznuCotrZdhPp6/CQNELMDJowTXUgbwdp7FUPss5Bp5WjMJHt+YIUw3vjaeucPawX2uzVyNjFY2pCG2IDl13LAvDEWuqMvB6NboX9uBFpW8ah0=
